# Assumption Register

**Project:** Sales Volatility, Promotion Effectiveness & Forecasting Benchmark Review
**Status:** Canonical governance document. Complements the Decision Log.
**Purpose:** The Decision Log explains why a decision was made. This register explains what each decision — and the analysis built on it — depends on. Every assumption below is explicit; none is left implicit in a notebook or recommendation.

---

| ID | Assumption | Source (Notebook / Decision) | Why This Assumption Exists | Potential Impact if False | Likelihood | Severity | Mitigation | Status |
|---|---|---|---|---|---|---|---|---|
| A01 | The removed incomplete record does not bias the analysis | Notebook 01 / D01 | A single row with ten missing fields was excluded rather than imputed | If the missingness were tied to a broader, undetected pattern rather than an isolated end-of-history artifact, other silent gaps could exist elsewhere in the dataset | Low | Low | Full-dataset missingness check performed in Notebook 01 found no other gap of any kind | Accepted |
| A02 | Promotion and non-promotion observations are independent enough for Mann-Whitney U | Notebook 03 / D02 | Mann-Whitney assumes independent observations; daily sales for the same SKU-store over time carry some autocorrelation, so independence is an approximation, not an exact property of this data | If autocorrelation is material, the reported p-value could be somewhat optimistic (appearing more significant than warranted), though the effect size (rank-biserial) would be less affected | Medium | Medium | Effect size reported alongside p-value throughout Notebook 03, specifically so a conclusion does not rest on the p-value alone | Needs Monitoring |
| A03 | Daily observations represent normal business operations | Notebook 01 / D01 | Stock-out days and the one discontinued SKU-store combination (SKU0004 × STORE0002) are atypical by definition | If atypical days were not correctly identified and handled, they would distort volatility and forecast-accuracy measures | Low | Low | Stock-out flag and discontinuation period explicitly identified and handled separately in Notebooks 01 and 03 | Accepted |
| A04 | Seasonality remains relatively stable across the observed three-year period | Notebook 03 (H4) / Notebook 04 (forecast baseline) | The Seasonal Historical Average and the seasonal hypothesis test both implicitly treat "June" in 2021, 2022, and 2023 as comparable | If the business or market shifted materially over the three years (new competitor, changed assortment, pricing strategy change), pooling all three years together would blur a real shift into a single averaged pattern | Medium | Medium | Not currently mitigated — no year-over-year stability check has been performed | Needs Monitoring |
| A05 | Weather measurements reasonably represent store operating conditions | Notebook 03 (H5) | Temperature and rainfall are recorded at some reference point (e.g., city-level), not necessarily at the store's exact location | If the weather data is a poor proxy for conditions actually experienced near the store, the "no measurable effect" finding could reflect a measurement gap rather than a genuine absence of a weather effect | Medium | Low | Finding is stated narrowly ("no measurable effect using these two weather measures"), not as a general claim about weather | Accepted |
| A06 | The two stores are analyzed only as these two specific stores; no conclusion is generalized beyond them | Notebooks 01, 03, 05 / D06 | Store, country, city, and channel are structurally confounded 1:1 in this dataset (one store per country per city per channel) | If a future reader generalizes a store-level finding to "channel type" or "market" in general, a conclusion would be drawn that this data cannot support | Low (within this project) / higher risk of downstream misuse | Critical if violated by a downstream reader | Explicit scope statement repeated in every notebook and in the README | Accepted |
| A07 | Missing cost data prevents ROI estimation; ROI is therefore intentionally excluded | Notebooks 01, 05 / D09 | No holding-cost, capital-cost, or promotion-spend field exists anywhere in the source dataset | None — this is a data-availability constraint, not a probabilistic assumption; the risk lies in a reader assuming ROI could be inferred indirectly | Low (confirmed absent) | Medium | Explicit "cannot be estimated" statements throughout Notebook 05 rather than a proxy estimate | Accepted |
| A08 | Historical data quality is sufficient after Notebook 01 cleaning | Notebook 01 | All subsequent notebooks build on the audited dataset without re-auditing | If the Notebook 01 audit missed an issue, every downstream statistic and forecast would inherit it silently | Low | Medium | Comprehensive audit (missingness, duplicates, type validation, date integrity, structural and numeric consistency checks) documented in Notebook 01 | Accepted |
| A09 | Seasonal Historical Average is an appropriate first forecasting benchmark | Notebook 04 / D07 | Chosen deliberately as the simplest, most explainable method before considering more complex alternatives | If the true underlying demand pattern has a component this method cannot capture (e.g., a trend), reported accuracy would be a floor, not a ceiling — understating what a more capable method could achieve | Low | Low | Explicitly framed as a benchmark, not a final forecasting system, throughout Notebook 04 | Accepted |
| A10 | The forecast benchmark is evaluated independently from planner judgement | Notebook 04 | No historical planner forecast data exists to compare against | A reader could mistakenly interpret the benchmark's 28.63% WAPE as "better than current planning" without any evidence for that comparison | Medium (risk of misinterpretation) | Medium | Notebook 04 and Notebook 05 both explicitly label this comparison "Insufficient Data" and recommend prospective logging to resolve it | Pending Validation |
| A11 | Recommendation confidence depends only on verified statistical evidence | Notebook 05 / D10 | Governance rule adopted to prevent an attractive but unevidenced idea from being recommended with the same confidence as a tested one | If not enforced consistently, a recommendation could carry more confidence than its underlying evidence supports | Low (self-imposed and checked) | High if violated | Explicit evidence-strength labeling and a dedicated "Recommendations NOT Supported" section in Notebook 05 | Accepted |
| A12 | Absence of statistical significance is not interpreted as evidence of no effect | Notebook 03 (H2, H5) | A "not supported" result (post-promotion dip, weather) means the specific test performed did not detect an effect — not that no effect could ever exist under any test | A reader could over-generalize "not supported" into "proven absent," particularly for weather (only two measures, same-day only, tested) and the post-promotion dip (only a 3-day window tested) | Medium | Medium | Findings phrased as "no evidence of X was found in this test," with the tested scope stated explicitly, rather than "X does not exist" | Needs Monitoring |

---

## Assumption Summary

- **Total assumptions:** 12
- **High-risk assumptions (Medium likelihood or above, combined with Medium+ severity):** A02 (Mann-Whitney independence), A04 (seasonal stability across 3 years), A10 (benchmark evaluated independently of planner judgement), A12 (non-significance misread as no effect)
- **Critical-severity assumptions:** A06 (store generalization) carries Critical severity if violated downstream, despite low likelihood within this project's own discipline; A11 (evidence-only recommendation confidence) carries High severity if the governance rule is not maintained
- **Assumptions requiring future validation:** A04 (year-over-year seasonal stability — not yet checked) and A10 (planner-vs-benchmark comparison — data does not yet exist to test this)
- **Assumptions intentionally left unresolved:** A07 (ROI is not estimated, by design, until cost data becomes available) and A10 (the benchmark-vs-planner comparison is deliberately left open rather than assumed in either direction)

No assumption in this register is presented as resolved when it is not. Where an assumption cannot yet be tested, this register states that directly rather than defaulting to an implicit "accepted" status.
